// <auto-generated />
using System;
using CloudShell.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudShell.Persistence.Migrations.CloudShell
{
    [DbContext(typeof(CloudShellDbContext))]
    partial class CloudShellDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LatestMigrationId => "20260606102257_InitialCreate";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("CloudShell.Persistence.ResourceGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceGroups", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceRegistrationEntity", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.HasIndex("ResourceGroupId");

                    b.ToTable("ResourceRegistrations", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceRegistrationEntity", b =>
                {
                    b.HasOne("CloudShell.Persistence.ResourceGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
