// <auto-generated />
using System;
using CloudShell.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudShell.Persistence.Migrations.CloudShell
{
    [DbContext(typeof(CloudShellDbContext))]
    partial class CloudShellDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LatestMigrationId => "20260613162026_AddResourceEvents";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("CloudShell.Persistence.ExtensionActivationEntity", b =>
                {
                    b.Property<string>("ExtensionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ExtensionId");

                    b.ToTable("ExtensionActivations", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TraceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ResourceEvents", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceGroups", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceRegistrationEntity", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.HasIndex("ResourceGroupId");

                    b.ToTable("ResourceRegistrations", (string)null);
                });

            modelBuilder.Entity("CloudShell.Persistence.ResourceRegistrationEntity", b =>
                {
                    b.HasOne("CloudShell.Persistence.ResourceGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
